In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
lst = [10, 20, 30, 40, 50]
arr = np.array(lst)
arr

array([10, 20, 30, 40, 50])

In [4]:
print("Size of array: ", arr.size)
print("data type of arr: ", arr.dtype)
print("shape of arr: ", arr.shape)
print("dimention of arr: ", arr.ndim,'D')
print("byten in arr: ", arr.nbytes)

Size of array:  5
data type of arr:  int32
shape of arr:  (5,)
dimention of arr:  1 D
byten in arr:  20


In [5]:
lst = [[10, 20, 30],
       [100, 200, 300]]
arr = np.array(lst)
arr

array([[ 10,  20,  30],
       [100, 200, 300]])

In [6]:
print("Size of array: ", arr.size)
print("data type of arr: ", arr.dtype)
print("shape of arr: ", arr.shape)
print("dimention of arr: ", arr.ndim,'D')
print("byten in arr: ", arr.nbytes)
print("type of arr: ", type(arr))

Size of array:  6
data type of arr:  int32
shape of arr:  (2, 3)
dimention of arr:  2 D
byten in arr:  24
type of arr:  <class 'numpy.ndarray'>


In [7]:
lst = [[1, 2, 3,],
       [4, 5, 6],
       [7, 8, 9]]

mat = np.matrix(lst)
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
print("Size of mat: ", mat.size)
print("data type of mat: ", mat.dtype)
print("shape of mat: ", mat.shape)
print("dimention of mat: ", mat.ndim,'D')
print("byten in mat: ", mat.nbytes)
print("type of mat: ", type(mat))

Size of mat:  9
data type of mat:  int32
shape of mat:  (3, 3)
dimention of mat:  2 D
byten in mat:  36
type of mat:  <class 'numpy.matrix'>


In [9]:
# addition and product:----

In [10]:
mat1 = mat
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
mat2 = np.matrix(np.array([[1, 3, 1],
                 [1, 2, 1],
                 [2, 1, 1]]))
mat2

matrix([[1, 3, 1],
        [1, 2, 1],
        [2, 1, 1]])

In [12]:
mat_add = mat1 + mat2
mat_add

matrix([[ 2,  5,  4],
        [ 5,  7,  7],
        [ 9,  9, 10]])

In [13]:
mat_mul = mat1 @ mat2
mat_mul

matrix([[ 9, 10,  6],
        [21, 28, 15],
        [33, 46, 24]])

In [14]:
# Slicing:---

In [15]:
mat = mat_mul
mat

matrix([[ 9, 10,  6],
        [21, 28, 15],
        [33, 46, 24]])

In [16]:
mat[1: , 1:]

matrix([[28, 15],
        [46, 24]])

In [17]:
mat[1: , -1]

matrix([[15],
        [24]])

In [18]:
# Generate Random Number:------

rn = np.random.randint(100)
rn

4

In [19]:
rn = np.random.randint(100, size=(4))
rn

array([ 8, 26, 82, 60])

In [20]:
rn = np.random.randint(100, size=(3,4))
rn

array([[28,  7, 50,  4],
       [93, 96, 42, 52],
       [18, 57, 80, 92]])

In [21]:
rn

array([[28,  7, 50,  4],
       [93, 96, 42, 52],
       [18, 57, 80, 92]])

In [22]:
rnn = np.random.rand(10)
rnn # generate random number in between 0 to 1

array([0.85286786, 0.2252744 , 0.87154928, 0.4029652 , 0.52801531,
       0.89788482, 0.36119076, 0.68760398, 0.27782314, 0.85323929])

In [23]:
rnn = np.random.rand(3,4)
rnn # generate random number in between 0 to 1, where shape is 3 rows and 4 columns

array([[0.92053908, 0.5762727 , 0.0233042 , 0.77401031],
       [0.44783884, 0.97244718, 0.10410942, 0.10475561],
       [0.48087647, 0.14016168, 0.04014684, 0.45669102]])

In [24]:
rnn = np.random.choice([10,20,30,40,50,60])
rnn

60

In [25]:
rnn = np.random.choice([10,20,30,40,50,60], size=(2, 2))
rnn

array([[40, 20],
       [40, 10]])

In [26]:
rnn = np.random.choice([10,20,30,40,50,60], size=(4,1))
rnn

array([[20],
       [20],
       [30],
       [30]])

In [27]:
rnn = np.random.choice([10,20,30,40,50,60], size=(10))
rnn

array([10, 50, 10, 30, 10, 30, 10, 40, 40, 40])

In [28]:
rnn = np.random.choice([10,20,30,40], p=[0.1, 0.3, 0.6, 0.0], size=(10))
rnn

array([30, 30, 20, 20, 20, 30, 20, 10, 20, 20])

In [29]:
# shuffle() and permutation() method:----------

a = np.array([10, 20, 30, 40, 50])
print(np.random.permutation(a))



[20 30 50 10 40]


In [30]:
a = np.array([[10, 20, 30],
              [100, 40, 50]
            ])

print(np.random.shuffle(a))

None


In [31]:
# Ones, zeros

one = np.ones((10))
zero = np.zeros((10))

print(one)
print(zero)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
one = np.ones((3, 4), dtype=int)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
zero = np.zeros((3, 4), dtype=int)
zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
one + zero

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
opt = np.ones((5,5))
opt

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [38]:
opt[1:4, 1:4] = z
opt

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.array([1, 2, 3, 4], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [42]:
np.array([1, 2, 3, 4], ndmin=2)

array([[1, 2, 3, 4]])

In [43]:
# shallow copy and deep copy:------------

In [44]:
# shallow copy:--

a = np.array([10, 20, 30, 40, 50])
b = a
b[0] = 255

print(a)
print(b)

[255  20  30  40  50]
[255  20  30  40  50]


In [45]:
# deep copy:--

a = np.array([10, 20, 30, 40, 50])
b = np.array(a, copy=True)
b[0] = 255

print(a)
print(b)

[10 20 30 40 50]
[255  20  30  40  50]


In [46]:
# deep copy:--

a = np.array([10, 20, 30, 40, 50])
b = np.array(a)
b[0] = 255

print(a)
print(b)

[10 20 30 40 50]
[255  20  30  40  50]


In [47]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
np.diag(x)

array([ 0,  5, 10])

In [49]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [50]:
np.diag(x, k=-1)

array([4, 9])

In [51]:
np.diag(np.diag(x))

array([[ 0,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 10]])

In [52]:
np.diag(np.diag(x, k=1))

array([[ 1,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 11]])

In [53]:
np.diagflat([1,2,3], k=0)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [55]:
np.tri(3,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [56]:
np.tril([[1,2,6], [3,4,5]])

array([[1, 0, 0],
       [3, 4, 0]])

In [57]:
np.triu([[1,2,6], [3,4,5]])

array([[1, 2, 6],
       [0, 4, 5]])

In [58]:
mat

matrix([[ 9, 10,  6],
        [21, 28, 15],
        [33, 46, 24]])

In [59]:
mat>6

matrix([[ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True]])

In [60]:
ind = np.where(mat>6)
ind

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 2, 0, 1, 2], dtype=int64))

In [61]:
mat[ind]

matrix([[ 9, 10, 21, 28, 15, 33, 46, 24]])

In [62]:
mat[mat>6]

matrix([[ 9, 10, 21, 28, 15, 33, 46, 24]])