# Numpy Arrays

In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to print the NumPy version in your system. 

np.__version__

'1.18.1'

In [5]:
# 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

mat = np.matrix(np.arange(2,11).reshape(3,3))
mat

matrix([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [7]:
# 3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

ar = np.zeros(10)
ar[6] = 11
ar

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [10]:
# 4. Write a NumPy program to reverse an array (first element becomes last).

ar = np.array([1, 2, 3, 4, 5])
sorted(ar, reverse=True)

[5, 4, 3, 2, 1]

In [11]:
# 5. Write a NumPy program to convert an array to a float type.

ar = np.array([1, 2, 3, 4, 5], dtype=float)
ar

array([1., 2., 3., 4., 5.])

In [15]:
one = np.ones((4,4))
zero = np.zeros((2,2))

one[1:3, 1:3] = zero
one

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [16]:
# 6. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. 

x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
# 7. Write a NumPy program to convert a list and tuple into arrays. 

tup = (1, 2, 3, 4, 5)
np.array(tup)

array([1, 2, 3, 4, 5])

In [24]:
# 8. Write a NumPy program to append values to the end of an array.

ar = np.array([10, 20, 30, 40, 50])
np.append(ar, 50)
ar

array([10, 20, 30, 40, 50])

In [30]:
# 9. Write a NumPy program to create an empty and a full array.

empty = np.empty((3,4))
full = np.full((3,4), 6)
empty, full

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]]))

In [38]:
# 10. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees.

lst = [0, 12, 45.21 ,34, 99.91]
def convertF(lst):
    F = []
    for i in lst:
        s = (((9*i)/5)+32)
        F.append(s)
    print(np.array(F))
convertF(lst)

[ 32.     53.6   113.378  93.2   211.838]


In [41]:
# 11. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

x = np.sqrt([1+0j])
y = np.sqrt([0+1j])

print(x.real)
print(y.real, '\n')

print(x.imag)
print(y.imag)

[1.]
[0.70710678] 

[0.]
[0.70710678]


In [48]:
# 12. Write a NumPy program to find the number of elements of an array, length of one 
# array element in bytes and total bytes consumed by the elements.

arr = np.array([10, 20, 30])

print("Length: ", len(arr))
print("Byte: ", arr.itemsize)
print("Total Bytes: ", arr.nbytes)

Length:  3
Byte:  4
Total Bytes:  12


In [49]:
# 13. Write a NumPy program to test whether each element of a 1-D array is also 
# present in a second array.

ar1 = np.array([ 0, 10, 20, 40, 60])
ar2 = np.array([0, 40])

np.in1d(ar1, ar2)

array([ True, False, False,  True, False])

In [53]:
# 14. Write a NumPy program to find common values between two arrays.

ar1 = np.array([ 0, 10, 20, 40, 60, 70, 80, 90, 100])
ar2 = np.array([10, 40, 110])

set(ar1) & set(ar2)

{10, 40}

In [54]:
# 15. Write a NumPy program to get the unique elements of an array. 

ar1 = np.array([ 0, 10, 20, 40, 10, 20, 80, 30, 40])
np.unique(ar1)

array([ 0, 10, 20, 30, 40, 80])

In [55]:
# 16. Write a NumPy program to find the union of two arrays. Union will return the unique, 
# sorted array of values that are in either of the two input arrays. 

ar1 = [ 0, 10, 20, 40, 60, 80]
ar2 = [10, 30, 40, 50, 70]

set(ar1).union(set(ar2))

{0, 10, 20, 30, 40, 50, 60, 70, 80}

In [58]:
# 17. Write a NumPy program to test whether all & any elements in an array evaluate to True.

ar1 = [10, 20, 10]
ar2 = [[True, False], [True, True]]
ar3 = [[True, True], [False, False]]
ar4 = [[True, True], [False, False]]
ar5 = [[10, 20], [30, 40]]
ar5 = [[10, 20], [20, 30]]

print("----------All------------\n")
print(np.all(np.array(ar1)))
print(np.all(np.array(ar2)))
print(np.all(np.array(ar3)))
print(np.all(np.array(ar4)))
print(np.all(np.array(ar5)))

print("\n----------Any------------\n")
print(np.any(np.array(ar1)))
print(np.any(np.array(ar2)))
print(np.any(np.array(ar3)))
print(np.any(np.array(ar4)))
print(np.any(np.array(ar5)))

----------All------------

True
False
False
False
True

----------Any------------

True
True
True
True
True


In [61]:
# 18. Write a NumPy program to construct an array by repeating. 

ar = [1, 2, 3, 4]

print("Repeating 2 times:---")
print(np.tile(np.array(ar), 2))

print("\nRepeating 3 times:---")
print(np.tile(np.array(ar), 3))

Repeating 2 times:---
[1 2 3 4 1 2 3 4]

Repeating 3 times:---
[1 2 3 4 1 2 3 4 1 2 3 4]


In [62]:
# 19. Write a NumPy program to repeat elements of an array. 

ar = np.array([[1, 2], [3, 4]])
print(np.repeat(ar, 2))

[1 1 2 2 3 3 4 4]


In [70]:
# 20. Write a NumPy program to find the indices of the maximum and minimum values 
# along the given axis of an array.

ar = np.array([11, 13, 1, 8, 20, 19])
print("Minimum: ", np.argmin(ar))
print("maximum: ", np.argmax(ar))

Minimum:  2
maximum:  4
