# Numpy Array

In [1]:
import numpy as np

In [3]:
# 1. Write a NumPy program compare two given arrays.

a = np.array([2,4])
b = np.array([5, 7])

a>b

array([False, False])

In [6]:
# 2. Write a NumPy program to sort an along the first, last axis of an array. 

a = np.array([[2,5],[4,4]])
np.sort(a, axis=1)

array([[2, 5],
       [4, 4]])

In [12]:
# 3. Write a NumPy program to get the values and indices of the elements that are bigger 
# than 10 in a given array. 

arr = np.array([[ 0, 10 ,20],[20, 30, 40]])
ind = np.where(arr>10)
ind

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [13]:
# 4. Write a NumPy program to save a NumPy array to a text file.

arr = np.array([[ 0, 10 ,20],[20, 30, 40]])
np.savetxt('file.out', arr, delimiter=',')

In [19]:
# 5. Write a NumPy program to find the memory size of a NumPy array.

arr = np.array([[ 0, 10 ,20],[20, 30, 40]])
arr.size * arr.itemsize

24

In [21]:
# 6. Write a NumPy program to create an array of ones and an array of zeros.

np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
# 7. Write a NumPy program to change the dimension of an array.

arr = np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# 8. Write a NumPy program to create a contiguous flattened array.
arr = np.array([[ 0, 10 ,20],[20, 30, 40]])
np.array(list(i for x in arr for i in x))

array([ 0, 10, 20, 20, 30, 40])

In [30]:
# 9. Write a NumPy program to change the data type of an array.

arr = np.array([[ 0, 10 ,20],[20, 30, 40]], dtype=float)
arr

array([[ 0., 10., 20.],
       [20., 30., 40.]])

In [31]:
# 10. Write a NumPy program to create a new array of 3*5, filled with 2. 

np.zeros((3,5), dtype=int)+2

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [32]:
# 11. Write a NumPy program to create an array of 10's with the same shape and type of a given array. 

x = np.arange(4, dtype=np.int64)
y = np.full_like(x, 10)
y

array([10, 10, 10, 10], dtype=int64)

In [38]:
# 12. Write a NumPy program to create a 2-D array with ones on a diagonal and zeros elsewhere.

np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [40]:
# 13. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] 
#     and 0's elsewhere.

x = np.array([4, 5, 6, 8])
np.diag(x)

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [41]:
# 14. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements 
# between 2.5. and 6.5, inclusive.

x = np.linspace(2.5, 6.5, 30)
x

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [42]:
# 15. Write a NumPy program to create an array which looks like tri-angle shape array.

np.tri(4, 3, -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [53]:
# 16. Write a NumPy program to find the 4th element of a specified array.

arr = np.array([[2, 4, 6], [6, 8, 10]])
arr.flat[3]

6

In [55]:
# 17. Write a NumPy program to interchange two axes of an array.

arr = [[1, 2, 3]]
np.swapaxes(arr, 0, 1)

array([[1],
       [2],
       [3]])

In [56]:
# 18. Write a NumPy program to move axes of an array to new positions. Other axes remain 
# in their original order. 

x = np.zeros((2, 3, 4))
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)

(3, 4, 2)
(4, 2, 3)


In [57]:
# 19. Write a NumPy program to move the specified axis backwards, until it lies in a given position.

x = np.ones((2,3,4,5))
print(np.rollaxis(x, 3, 1).shape)

(2, 5, 3, 4)


In [58]:
# 20. Write a NumPy program to convert specified inputs to arrays with at least one dimension.

x = 12.0
print(np.atleast_1d(x))
x = np.arange(6.0).reshape(2, 3)
print(np.atleast_1d(x))
print(np.atleast_1d(1, [3, 4]))

[12.]
[[0. 1. 2.]
 [3. 4. 5.]]
[array([1]), array([3, 4])]


In [59]:
# start at 55