# Numpy Random

In [1]:
import numpy as np

In [3]:
# 1. Write a NumPy program to generate five random numbers from the normal distribution. 

np.random.normal(size=5)

array([-0.7481142 , -0.59919543, -0.34878222, -0.34507686,  0.11784219])

In [5]:
# 2. Write a NumPy program to generate six random integers between 10 and 30.

np.random.randint(low=10, high=30, size=6)

array([24, 21, 15, 17, 14, 20])

In [6]:
# 3. Write a NumPy program to create a 3x3x3 array with random values.

np.random.normal(size=27).reshape(3,3,3)

array([[[-1.53951616,  0.03770242,  1.0197106 ],
        [-1.29295768, -0.04865024,  0.69272347],
        [ 0.78961382, -0.44512588,  0.97007635]],

       [[ 2.11851451,  0.31875981, -0.38404464],
        [ 0.0577378 ,  1.87360775, -1.59751651],
        [-0.92625973,  0.42516489, -0.25394581]],

       [[-0.23398064,  0.26736323,  0.95277582],
        [-0.42118052,  1.00437689, -0.65456435],
        [-2.51791884,  0.25616415, -1.92543133]]])

In [11]:
# 4. Write a NumPy program to create a 5x5 array with random values and find the minimum 
# and maximum values.

mat = np.random.randint(low=10, high=40, size=25).reshape(5,5)
max, min = mat.max(), mat.min()
max, min

(38, 10)

In [16]:
# 5. Write a NumPy program to create a random 10x4 array and extract the first five rows of 
# the array and store them into a variable. 

mat = np.random.randint(low=10, high=140, size=40).reshape(10,4)
mat[0:5]

array([[ 28, 136, 115,  19],
       [ 42,  58,  40, 131],
       [ 83,  33, 114,  21],
       [ 49,  93, 102,  48],
       [ 52,  24,  32,  79]])

In [21]:
# 6. Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

arr = np.array([10, 20, 30, 40, 50])
print(arr)
np.random.shuffle(arr)
print(arr)

[10 20 30 40 50]
[40 30 10 50 20]


In [25]:
# 7. Write a NumPy program to normalize a 3x3 random matrix.

arr = np.random.randint(low=10, high=50, size=9).reshape(3,3)
print(arr, '\n')

max, min = arr.max(), arr.min()
arr = (arr - min)/(max-min)

print("After Normalization: \n", arr)

[[41 42 48]
 [26 30 32]
 [10 21 30]] 

After Normalization: 
 [[0.81578947 0.84210526 1.        ]
 [0.42105263 0.52631579 0.57894737]
 [0.         0.28947368 0.52631579]]


In [28]:
# 8. Write a NumPy program to create a random vector of size 10 and sort it.

arr = np.random.normal(size=10)
print(arr, '\n')
print(sorted(arr))

[ 1.34827022 -0.27224281  0.43981299  1.20307761  1.19807365 -0.43967687
 -0.47299679  1.51708936  0.47036873 -0.49883227] 

[-0.49883226822508453, -0.4729967926516914, -0.4396768706070091, -0.27224280963266334, 0.43981298843739736, 0.47036873251955647, 1.1980736490029178, 1.2030776057182655, 1.3482702203217753, 1.5170893645536032]


In [29]:
# 9. Write a NumPy program to find the nearest value from a given value in an array.

x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

2.366763802512443


In [35]:
# 10. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1

arr = np.random.normal(size=15)
print(arr, '\n')

max = arr.max()
ind = np.where(arr == max)
arr[ind]

[ 0.32950664  1.75205998  0.56229311  0.26812787 -0.78194563 -0.93644962
 -2.19863998  0.58198899 -0.37223706  0.9101946  -0.13161939 -1.40421355
  2.43391295 -0.79487558 -0.1270542 ] 



array([2.43391295])

In [36]:
# 11. Write a NumPy program to find point by point distances of a random vector with 
# shape (10,2) representing coordinates.

a = np.random.random((10,2))
x, y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.88935391 0.8450646  0.62954132 0.48007817 0.51952421
  0.21664133 1.02148206 0.54209848 0.92708626]
 [0.88935391 0.         0.28874822 0.50699461 0.47063715 0.63946773
  0.69781834 0.15407688 0.51240312 0.5938791 ]
 [0.8450646  0.28874822 0.         0.28660193 0.56379757 0.77469009
  0.70339927 0.42052875 0.65143015 0.30569522]
 [0.62954132 0.50699461 0.28660193 0.         0.52359859 0.73547596
  0.5473666  0.65916297 0.63648561 0.30293967]
 [0.48007817 0.47063715 0.56379757 0.52359859 0.         0.21679398
  0.26435552 0.57427616 0.1158191  0.79114843]
 [0.51952421 0.63946773 0.77469009 0.73547596 0.21679398 0.
  0.3260618  0.71037399 0.12808    1.00785368]
 [0.21664133 0.69781834 0.70339927 0.5473666  0.26435552 0.3260618
  0.         0.82066653 0.3282046  0.84905505]
 [1.02148206 0.15407688 0.42052875 0.65916297 0.57427616 0.71037399
  0.82066653 0.         0.58998128 0.71736107]
 [0.54209848 0.51240312 0.65143015 0.63648561 0.1158191  0.12808
  0.3282046  0.58998128 

In [40]:
# 12. Write a NumPy program to find the most frequent value in an array. 

arr = np.random.randint(low=10, high=50, size=20)
print(arr, '\n')
print(np.bincount(arr).argmax())

[21 39 47 40 10 46 21 36 32 37 43 28 24 34 37 27 45 42 26 14] 

21


In [41]:
# 13. Write a NumPy program to find the closest value (to a given scalar) in an array.

x = np.arange(100)
print(x, '\n')

a = np.random.uniform(0, 100)
print(a, '\n')

ind = (np.abs(x-a)).argmin()
x[ind]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 

4.571557419140038 



5

In [43]:
# 14. Write a NumPy program to get the n largest values of an array.

arr = np.array([10, 2, 7, 90, 11, 21, 27])
arr.max()

90