# Numpy Mathematics

In [1]:
import numpy as np

In [3]:
# 1. Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, 
# sum of exponentiations of the inputs in base-2.

l1 = np.log(1e-50)
l2 = np.log(2.5e-50)
print("Logarithm of the sum of exponentiations:")
print(np.logaddexp(l1, l2))
print("Logarithm of the sum of exponentiations of the inputs in base-2:")
print(np.logaddexp2(l1, l2))

Logarithm of the sum of exponentiations:
-113.87649168120691
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.59955522772194


In [4]:
# 2. Write a NumPy program to get true division of the element-wise array inputs. 

arr = np.array([0, 1, 2, 3, 4, 5, 6])
np.true_divide(arr, 3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [5]:
# 3. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs. 

x = [1., 2., 3., 4., 5.]
np.floor_divide(x, 1.5)

array([0., 1., 2., 2., 3.])

In [7]:
# 4.  Write a NumPy program to get the powers of an array values element-wise

arr = np.array(np.arange(6))
res = lambda x: x**3
res(arr)

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [8]:
# 5. Write a NumPy program to get the element-wise remainder of an array of division.

arr = np.array(np.arange(6))
np.remainder(arr, 5)

array([0, 1, 2, 3, 4, 0], dtype=int32)

In [11]:
# 6. Write a NumPy program to calculate the absolute value element-wise.

arr = np.array([-20.6, 10, 12, -7.5, 50])
np.abs(arr)

array([20.6, 10. , 12. ,  7.5, 50. ])

In [14]:
# 7. Write a NumPy program to round array elements to the given number of decimals.

arr = np.array([0.45, 1.25, 2.0, 5.10, 10, 20.5])
n1 = np.round(arr, decimals=1)
n2 = np.round(arr)

print(n1, '\n')
print(n2)

[ 0.4  1.2  2.   5.1 10.  20.5] 

[ 0.  1.  2.  5. 10. 20.]


In [15]:
# 8.  Write a NumPy program to round elements of the array to the nearest integer.

arr = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])
np.rint(arr)

array([-1., -2., -2.,  0.,  2.,  2.,  2.])

In [18]:
# 9. Write a NumPy program to get the floor, ceiling and truncated values of the elements 
# of a numpy array. 

arr = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
floor = np.floor(arr)
ceil = np.ceil(arr)
trun = np.trunc(arr)

print(floor)
print(ceil)
print(trun)

[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]
[-1. -1. -0.  0.  1.  1.  2.]


In [19]:
# 10. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

ar1 = np.random.randint(low=10, high=50, size=15).reshape(5, 3)
ar2 = np.random.randint(low=1, high=10, size=6).reshape(3, 2)

dot = np.dot(ar1, ar2)
dot

array([[803, 624],
       [903, 684],
       [641, 404],
       [941, 688],
       [523, 392]])

In [24]:
# 11. Write a NumPy program to create an inne product of two arrays.

arr = np.arange(24).reshape((2,3,4))
y = np.arange(4)

inner = np.inner(arr, y)
print(inner, '\n')

[[ 14  38  62]
 [ 86 110 134]] 



In [25]:
# 12. Write a NumPy program to generate a matrix product of two arrays. 

ar1 = np.array([[2, 5], [1, 2]])
ar2 = np.array([[1, 2,], [3, 1]])

ar1@ar2

array([[17,  9],
       [ 7,  4]])