# Numpy Statistics

In [1]:
import numpy as np

In [2]:
# 1. Write a Python program to find the maximum and minimum value of a given flattened array. 

arr = np.array([[10, 12], [20, 19]])
arr.max()

20

In [3]:
# 2. Write a NumPy program to get the minimum and maximum value of a given array 
# along the second axis. 

arr = np.array([[10, 12], [20, 19]])
arr.max(axis=1)

array([12, 20])

In [9]:
# 3. Write a NumPy program to calculate the difference between the maximum and the 
# minimum values of a given array along the second axis.

arr = np.array([[1, 12, 10], [20, 14, 1]])
amax = arr.max(axis=1)
amin = arr.min(axis=1)

amax - amin

array([11, 19])

In [12]:
# 4. Write a NumPy program to compute the 80th percentile for all elements in a given array 
# along the second axis.

arr = np.array([1.0, 2.0, 3.0, 4.0])
np.percentile(arr, 80)

3.4000000000000004

In [13]:
# 5. Write a NumPy program to compute the median of flattened given array.

arr = np.array(np.arange(1, 11))
np.median(arr)

5.5

In [14]:
# 6. Write a NumPy program to compute the weighted of a given array.

x = np.arange(5)
print("\nOriginal array:")
print(x)
weights = np.arange(1, 6)
r1 = np.average(x, weights=weights)
r2 = (x*(weights/weights.sum())).sum()
assert np.allclose(r1, r2)
print("\nWeighted average of the said array:")
print(r1)


Original array:
[0 1 2 3 4]

Weighted average of the said array:
2.6666666666666665


In [20]:
# 7. Write a NumPy program to compute the mean, standard deviation, and variance of a 
# given array along the second axis.

arr = np.array(np.arange(1, 12))
mean = np.mean(arr)
sd = np.std(arr)


mean, mean, sd

(6.0, 6.0, 3.1622776601683795)

In [24]:
# 8. Write a NumPy program to compute the covariance matrix of two given arrays.

arr1 = np.array(np.arange(1, 12))
arr2 = np.array(np.arange(12, 1, -1))
cov = np.cov(arr1, arr2)
cov

array([[ 11., -11.],
       [-11.,  11.]])

In [25]:
# 9. Write a NumPy program to compute pearson product-moment correlation 
# coefficients of two given arrays.

arr1 = np.array(np.arange(1, 12))
arr2 = np.array(np.arange(12, 1, -1))

cov = np.corrcoef(arr1, arr2)
cov

array([[ 1., -1.],
       [-1.,  1.]])

In [26]:
# 10. Write a Python NumPy program to compute the weighted average along the specified axis 
# of a given flattened array.

arr = np.array([[2, 3, 5], [1, 2, 3], [10, 11, 12]])
np.average(arr, axis=1, weights=[1./4, 2./4, 2./4])

array([ 3.6,  2.2, 11.2])